[metadata]
name = "NestJs Api"
[[variables]]
field = "author"
prompt = "Project's author?: "
default = "arekkazu"
[[variables]]
field = "description"
prompt = "Project Description: "
default = "Building an API using NestJs"



